FROM openjdk:8-jdk

RUN apt-get update && apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app

# Install required Python packages.
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN chmod +x gradlew

# Expose both the voting-phase and decision-phase ports.
# (They will be provided via environment variables.)
# EXPOSE 50051 60051

