FROM openjdk:8-jdk

# Install Python3 and pip.
RUN apt-get update && apt-get install -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
# Copy your entire project into the container.
COPY . /app

# Install required Python packages.
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make the Gradle wrapper executable.
RUN chmod +x gradlew

# Expose the port used by the DecisionCoordinator service.
# EXPOSE 60060

