# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: twopc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'twopc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btwopc.proto\x12\x05twopc\"#\n\x0bVoteRequest\x12\x14\n\x0cvote_request\x18\x01 \x01(\t\"#\n\x0cVoteResponse\x12\x13\n\x0bvote_commit\x18\x01 \x01(\x08\x32\x45\n\x0bVotingPhase\x12\x36\n\x0bRequestVote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twopc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOTEREQUEST']._serialized_start=22
  _globals['_VOTEREQUEST']._serialized_end=57
  _globals['_VOTERESPONSE']._serialized_start=59
  _globals['_VOTERESPONSE']._serialized_end=94
  _globals['_VOTINGPHASE']._serialized_start=96
  _globals['_VOTINGPHASE']._serialized_end=165
# @@protoc_insertion_point(module_scope)
